spring:
  application:
    name: graa-backend
  datasource:
    url: "jdbc:postgresql://172.17.0.1:5432/graa-backend"
    username: "observer"
    password: "1111"
server:
  port: 8000

logging:
  level:
    org.springframework.security: DEBUG