spring:
  application:
    name: graa-backend
  datasource:
#    url: "jdbc:postgresql://172.17.0.1:5432/graa_backend"
#    username: "observer"
#    password: "1111"
    url: "jdbc:postgresql://localhost:5432/graa-database"
    username: "postgres"
    password: "root"

server:
  port: 8000


logging:
  level:
    org.springframework.security: DEBUG
